#import "@preview/lasaveur:0.1.3": *
// Currently, a patched version of touying is needed
#import "@preview/touying:0.6.1": *
// #import "touying/src/core.typ": *  
// patched version no longer needed
#import "p2vmeta.typ": *

#t2sdefaults(
  transition: "fade",
  transition_duration: 0.8,
)

#pdfpc.config(
  disable-markdown: false,
  default-transition: (
    type: "fade",
    duration-seconds: 1,
    // angle: ltr,
    // alignment: "vertical",
    // direction: "inward",
  ),
)

#import themes.university: *
// #import "touying/themes/university.typ": *
// patched version no longer needed

#import "@preview/numbly:0.1.0": numbly

#show: university-theme.with(
  aspect-ratio: "16-9",
  config-info(
    title: [touying2video],
    subtitle: [Converting Typst presentations to video],
    author: [Paul Yang],
    date: [], // datetime.today(),
    institution: [],
    logo: emoji.school,
  ),
)

// #set heading(numbering: numbly("{1}.", default: "1.1"))

#title-slide()
#t2s[
  In this video, I am going to demonstrate the functionality of the touying to video tool.
]

== Advantages

#slide[
  - Automatic process
  #pause
  - Animation support
  #pause
  - Multiple text-to-speech backends
  #t2s(start_from: 1)[Our tool can convert Typst presentations generated by touying to a presentation video with AI voiceover.]
  #t2s(start_from: 2)[
    It has good supports for animation.  For example, 
    I can configure the tool so that 
    the next bullet point will not appear until the current sentence is finished.
  ]
  #t2s(start_from: 3)[
    The tool supports multiple text-to-speech backends.  Currently, it supports Baidu's PaddlePaddle and OpenAI's TTS.
  ]
]

#slide[
  You can also use some hacks to generate animations.
  #duration(physical: (2, 1, 1, 1, 1, 1, 1))
  #t2s(start_from: 1)[
    You can also use some hacks to generate animations.
  ]
  #t2s(start_from: 2)[]

  #text(size: 100pt)[
    #set align(center)
    #only("2, 4, 6")[
      😀
    ]
    #only("3, 5, 7")[
      😄
    ]
  ]
]

== Liminations

#slide[
  - Currently, patched version of touying is needed
  #t2s(start_from: 1)[However, there are some limitations Currently, a patched version of touying is needed.]
  #pause
  - Rather slow video generated speed (due to MoviePy)
  #t2s(start_from: 2)[Its video generation speed is rather slow.  This is due to the fact that it uses MoviePy to generate videos.]
]

#context t2s-file(here())
