tts_tool: chattts  # May be openai or peddlespeech or chattts or load
openai:
  model: 'tts-1-hd'
  voice: 'ash'
  api_key: './api_key.txt'
  speed: 1

paddlespeech:
  lang: 'en'
  voc: 'hifigan_ljspeech'
  am: 'fastspeech2_ljspeech'

chattts:
  speaker: 'speaker_man_calm_2.pt'
  speaker_save_path: null


load:
  path: './tmp_demo/'
