tts_tool: paddlespeech  # May be openai or peddlespeech
openai:
  model: 'tts-1-hd'
  voice: 'ash'
  api_key: './api_key.txt'
  speed: 1

paddlespeech:
  lang: 'en'
  voc: 'hifigan_ljspeech'
  am: 'fastspeech2_ljspeech'

