tts_tool: openai  # May be openai or peddle
openai:
  model: 'tts-1-hd'
  voice: 'ash'
  api_key: './api_key.txt'
  speed: 1

peddle:
  lang: 'en'
  voc: 'hifigan_ljspeech'
  am: 'fastspeech2_ljspeech'

